
DROP TABLE IF EXISTS pertinence ;
DROP TABLE IF EXISTS aimer;
DROP TABLE IF EXISTS preferer;
DROP TABLE IF EXISTS avoir;
DROP TABLE IF EXISTS posseder;
DROP TABLE IF EXISTS concerner;
DROP TABLE IF EXISTS illustrer;
DROP TABLE IF EXISTS creer;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS categorie;
DROP TABLE IF EXISTS jeu;
DROP TABLE IF EXISTS theme;
DROP TABLE IF EXISTS personne;
DROP TABLE IF EXISTS joueur;
