

CREATE TABLE JOUEUR (
    ID_JOUEUR INT NOT NULL,
    PSEUDO CHAR(30) NOT NULL unique,
    NOM CHAR(30),
    PRENOM CHAR(30),
    MAIL CHAR(100),
    constraint pk_joueur PRIMARY KEY(ID_JOUEUR)
);


CREATE TABLE NOTE (
    ID_NOTE INT NOT NULL,
    ID_JOUEUR INT NOT NULL,
    SCORE INT NOT NULL,
    COMMENTAIRE VARCHAR(1000),
    DATE_NOTE DATE NOT NULL,
    NB_JOUEURS INT,
    constraint pk_note PRIMARY KEY(ID_NOTE),
    constraint fk_note FOREIGN KEY (ID_JOUEUR) REFERENCES JOUEUR(ID_JOUEUR)

);


CREATE TABLE PERTINENCE (
    ID_NOTE INT NOT NULL,
    ID_JOUEUR INT NOT NULL,
    PERTINENT BOOLEAN NOT NULL,
    constraint pk_pertinence PRIMARY KEY(ID_JOUEUR, ID_NOTE),
    constraint fk_pertinence_joueur FOREIGN KEY (ID_JOUEUR) REFERENCES JOUEUR(ID_JOUEUR),
    constraint fk_pertinence_note FOREIGN KEY (ID_NOTE) REFERENCES NOTE(ID_NOTE)
);


CREATE TABLE THEME (
    ID_THEME INT NOT NULL,
    NOM CHAR(30) NOT NULL unique,
    constraint pk_theme PRIMARY KEY(ID_THEME)
);


CREATE TABLE CATEGORIE (
    ID_CATEGORIE INT NOT NULL,
    NOM CHAR(30) NOT NULL unique,
    constraint pk_categorie PRIMARY KEY(ID_CATEGORIE)
);


CREATE TABLE AIMER (
    ID_JOUEUR INT NOT NULL,
    ID_THEME INT NOT NULL,
    constraint pk_aimer PRIMARY KEY(ID_JOUEUR, ID_THEME),
    constraint fk_aimer_joueur FOREIGN KEY (ID_JOUEUR) REFERENCES JOUEUR(ID_JOUEUR),
    constraint fk_aimer_theme FOREIGN KEY (ID_THEME) REFERENCES THEME(ID_THEME)
);


CREATE TABLE PREFERER (
    ID_JOUEUR INT NOT NULL,
    ID_CATEGORIE INT NOT NULL,
    constraint pk_preferer PRIMARY KEY(ID_JOUEUR, ID_CATEGORIE),
    constraint fk_preferer_joueur FOREIGN KEY (ID_JOUEUR) REFERENCES JOUEUR(ID_JOUEUR),
    constraint fk_preferer_categorie FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE)
);

CREATE TABLE JEU (
    ID_JEU INT NOT NULL,
    NOM VARCHAR(100) NOT NULL unique,
    EDITEUR CHAR(30) NOT NULL,
    ANNEE_PARUTION INT NOT NULL,
    DUREE INT NOT NULL,
    NB_JOUEURS INT NOT NULL,
    EXTENSION BOOLEAN NOT NULL,
    ID_JEU_IF_EXTENSION INT,
    constraint pk_jeu PRIMARY KEY(ID_JEU),
    constraint fk_etendre_jeu FOREIGN KEY (ID_JEU_IF_EXTENSION) REFERENCES JEU(ID_JEU)
);


CREATE TABLE AVOIR (
    ID_JEU INT NOT NULL,
    ID_THEME INT NOT NULL,
    constraint pk_avoir PRIMARY KEY(ID_JEU, ID_THEME),
    constraint fk_avoir_jeu FOREIGN KEY (ID_JEU) REFERENCES JEU(ID_JEU),
    constraint fk_avoir_theme FOREIGN KEY (ID_THEME) REFERENCES THEME(ID_THEME)
);


CREATE TABLE POSSEDER (
    ID_JEU INT NOT NULL,
    ID_CATEGORIE INT NOT NULL,
    constraint pk_posseder PRIMARY KEY(ID_JEU, ID_CATEGORIE),
    constraint fk_posseder_jeu FOREIGN KEY (ID_JEU) REFERENCES JEU(ID_JEU),
    constraint fk_posseder_categorie FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE)
);


CREATE TABLE CONCERNER (
    ID_NOTE INT NOT NULL,
    ID_JEU INT NOT NULL,
    constraint pk_concerner PRIMARY KEY(ID_JEU, ID_NOTE),
    constraint fk_concerner_note FOREIGN KEY (ID_NOTE) REFERENCES NOTE(ID_NOTE),
    constraint fk_concerner_jeu FOREIGN KEY (ID_JEU) REFERENCES JEU(ID_JEU)
);


CREATE TABLE PERSONNE (
    ID_PERSONNE INT NOT NULL,
    NOM CHAR(30) NOT NULL,
    PRENOM CHAR(30),
    constraint pk_personne PRIMARY KEY(ID_PERSONNE)
);


CREATE TABLE ILLUSTRER (
    ID_JEU INT NOT NULL,
    ID_PERSONNE INT NOT NULL,
    constraint pk_illustrer PRIMARY KEY(ID_JEU, ID_PERSONNE),
    constraint fk_illustrer_jeu FOREIGN KEY (ID_JEU) REFERENCES JEU(ID_JEU),
    constraint fk_illustrer_personne FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE(ID_PERSONNE)
);


CREATE TABLE CREER (
    ID_JEU INT NOT NULL,
    ID_PERSONNE INT NOT NULL,
    constraint pk_creer PRIMARY KEY(ID_JEU, ID_PERSONNE),
    constraint fk_creer_jeu FOREIGN KEY (ID_JEU) REFERENCES JEU(ID_JEU),
    constraint fk_creer_personne FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE(ID_PERSONNE)
);
